# The logging configuration. On a real server this will be a file url. e.g. file://{{ monitoring_tests_dir }}/logback.xml
logging:
  config: classpath:logback.xml

server:
  # The port to where this Spring Boot application listens to. e.g. http://localhost:{{ springapp_tcpport }}
  port: 9000
  # The context path of the server. You can skip this value in the overriding application.yml on the classpath
  contextPath:

eb:
  metadata_idp_url: https://engine.test2.surfconext.nl/authentication/idp/metadata
  metadata_sp_url: https://engine.test2.surfconext.nl/authentication/sp/metadata
  mujina_sp_base_url: https://mujina-sp.test2.surfconext.nl
  mujina_idp_entity_id: http://mock-idp
  mujina_username: monitor-user

pdp:
  user: pdp_admin
  password: secret
  idp_entity_id: https://engine.test2.surfconext.nl/authentication/idp/metadata
  sp_entity_id: https://engine.test2.surfconext.nl/authentication/sp/metadata
  base_url: https://pdp.test2.surfconext.nl

voot:
  oidc:
    authorization_url: https://oidc.test2.surfconext.nl/token
    voot_base_url: https://voot.test2.surfconext.nl
    client_id: https@//authz-playground.test2.surfconext.nl
    secret: secret
    person_id: urn:collab:person:example.com:admin

oidcng:
  base_url: https://connect.test2.surfconext.nl/oidc
  client_id: playground_client
  secret: secret
  resource_server_id: resource-server-playground-client
  resource_server_secret: secret


# We disable all endpoints except health for the load-balancer and info for git information.
management:
  endpoints:
    web:
      exposure:
        include: "health,info,mappings"
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
    mappings:
      enabled: true
  info:
    git:
      mode: full

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
security:
  user:
    name: user
    password: secret
